stages:
- build
- purge

variables:
  GIT_SUBMODULE_STRATEGY: recursive

image: hub.docker.faereal.net:443/tokonatsu/docker/hugo-builder:latest

hugo build live:
  stage: build
  script:
    - hugo --baseURL https://colinbarker.me.uk/
    - aws s3 sync --delete --acl public-read public s3://colinbarker.me.uk
  tags:
    - docker
  only:
    - master

cloudflare purge cache:
  stage: purge
  script: >-
    curl -X POST "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/purge_cache" -H "Authorization: Bearer $CLOUDFLARE_API_KEY" -H "Content-Type:application/json" --data '{"purge_everything":true}'
  tags:
    - docker