baseurl                 = "https://colinbarker.me.uk/"
languageCode            = "en-gb"
title                   = "Colin Barker: Cloud Consultant"
theme                   = "hugo-future-imperfect-slim"
paginate                = 3
disqusShortname         = ""
googleAnalytics         = ""
pluralizeListTitles     = false
disableLanguages        = [""]

[outputs]
  home                  = ["html", "json"]


[params]
  enableCDN             = false
  cssFiles              = ["default"]
  jsFiles               = ["default"]
  highlightjs           = true
  highlightjsTheme      = "github"
  highlightjsLang       = ["html", "css", "js", "toml"]
  viewMorePostsLink     = "/blog/"
  readingTime           = true
  socialShare           = ["twitter", "facebook", "reddit", "linkedin", "pinterest", "email"]

[params.meta]
	description         = "Some text below. Powered by Hugo."
	author              = "Colin Barker"
	favicon             = false
	svg                 = true
	faviconVersion      = "1"
	msColor             = "#ffffff"
	iOSColor            = "#ffffff"

[params.header]
	navbarTitle         = "Colin Barker"
	dynamicTitles       = true
	searchMenu          = true
	shareMenu           = true
	languageMenu        = false

[params.intro]
	header                = "Colin Barker"
	paragraph             = "Cloud Consultant"
	rssIntro              = true
	socialIntro           = true
	hideWhenSingleColumn  = false
	alwaysOnHomepage      = false

	[params.intro.pic]
		src                 = "/img/main/profile_pic.jpg"
		shape               = "circle"
		width               = ""
		alt                 = "Colin Barker"

[params.sidebar]
  about               = "A cloud solutions architect, geek, tinkerer, and geocacher."
  postAmount          = 5
  categories          = true
  categoriesByCount   = true

[params.footer]
  rssFooter           = true
  socialFooter        = true


[menu]

	[[menu.main]]
		name              = "Home"
		identifier        = "home"
		url               = "/"
		pre               = "<i class='fa fa-home'></i>"
		weight            = 1

	[[menu.main]]
		name              = "About"
		identifier        = "about"
		url               = "/about/"
		pre               = "<i class='far fa-id-card'></i>"
		weight            = 2


[social]
	# Coding Communities
	github                = "mystcb"
	gitlab                = "mystcb"
    flickr                = "mystcb"
    linkedin              = "colinbarker"
    facebook              = "mystcb"
    youtube               = "mystcb"
    instagram             = "mystcb"
    twitter               = "mystcb"
