baseurl:                 https://colinbarker.me.uk/
languageCode:            en-gb
title:                   Colin Barker
theme:                   hugo-theme-stack
paginate:                5
DefaultContentLanguage: "en"
hasCJKLanguage:         false
disqusShortname         : ""
googleAnalytics         : ""

permalinks:
    post: /blog/:slug/
    page: /:slug/

params:
    mainSections:
        - blog
    featuredImageField: image
    rssFullContent: true

    footer:
        since: 2020
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 BST    

    sidebar:
        emoji: 
        subtitle: Head of AWS & Management Consultant, AWS Ambassador, AWS Certification Lead Subject Matter Expert (CLSME), AWS Community Builder, and Chairman of Tokonatsu, a Japanese Culture Festival.
        avatar:
            enabled: true
            local: true
            src: /img/profile_pic.jpg

    widgets:
        homepage:
            - type: search
            - type: archives
              params:
                  limit: 5
            - type: categories
              params:
                  limit: 10
            - type: tag-cloud
              params:
                  limit: 10
        page:
            - type: toc

markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: false
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: true
        tabWidth: 4

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main: []

    social:
        - identifier: github
          name: GitHub
          url: https://github.com/mystcb
          params:
              icon: brand-github

        - identifier: x
          name: X
          url: https://twitter.com/mystcb
          params:
              icon: brand-x 

        # - identifier: flickr
        #   name: Twitter
        #   url: https://flickr.com/photos/mystcb
        #   params:
        #       icon: brand-flickr   

        - identifier: linkedin
          name: LinkedIn
          url: https://linkedin.com/in/colinbarker
          params:
              icon: brand-linkedin

        - identifier: facebook
          name: Facebook
          url: https://facebook.com/mystcb
          params:
              icon: brand-facebook

        - identifier: instagram
          name: Instagram
          url: https://instagram.com/mystcb
          params:
              icon: brand-instagram

        - identifier: youtube
          name: YouTube
          url: https://youtube.com/mystcb
          params:
              icon: brand-youtube

        - identifier: mastadon
          name: Mastadon
          url: https://tokonatsu.social/@myst
          params:
              icon: brand-mastodon