name: Website Build and Deploy

on:
  push:
    branches:    
    - main

jobs:
  hugo_build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.81.0'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Build Live Site
        if: contains( github.ref, 'main')
        run: hugo --baseURL https://colinbarker.me.uk/

      - name: Deploy Live Site
        if: contains( github.ref, 'main')
        run: aws s3 sync --delete --acl public-read public s3://colinbarker.me.uk

  cloudflare_purge_cache:
    runs-on: ubuntu-latest
    needs: [ hugo_build_and_deploy ]
    steps:
      - name: Clear CloudFlare cache
        env:
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/purge_cache" -H "Authorization: Bearer $CLOUDFLARE_API_KEY" -H "Content-Type:application/json" --data '{"purge_everything":true}'